---
- hosts: devapp
  become: true
  tasks:
    - name: Install list of packages
      yum: name='{{item}}' state=present
      with_items:
       - httpd
       - wget
       - vim
       - zip
       - unzip  
...

