node {
    def resultImage
    def voteImage
    def workerImage
    docker.withRegistry("https://index.docker.io/v1/", "Docker_Hub" ) {
      stage('Clone repo') {
        checkout scm
      }
      stage('Build result') {
        resultImage = docker.build("tno35/result-app:v1.0.1", "./result")
      }
      stage('Build vote') {
        voteImage = docker.build("tno35/vote-app:v1.0.1", "./vote")
      }
      stage('Build worker dotnet') {
        workerImage = docker.build("tno35/worker-app:v1.0.1", "./worker")
      }
      stage('Push result image') {
          resultImage.push("${env.BUILD_NUMBER}")
          resultImage.push()
        }
      stage('Push vote image') {
          voteImage.push("${env.BUILD_NUMBER}")
          voteImage.push()
      }
      stage('Push worker image') {
          workerImage.push("${env.BUILD_NUMBER}")
          workerImage.push()
      }
    }
}
